# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:month-:day-:year/:title.html
gems:     [jekyll-paginate]
markdown: kramdown
highlighter: rouge
# Setup
title:               何先生的blog
tagline:             'DataGridView'
description:         'The module is powered by<a href="https://twitter.com/mdo" target="_blank">@mdo</a>.<br>Redesigned by a small little cute<br><a href="http://weibo.com/u/2923167807">@城南走位王何老汉</a>'
url:                 http://lanyon.getpoole.com
baseurl:             '/blog/'
paginate:            20

# About/contact
author:
  name:              He Yunfan
  url:               https://twitter.com/mdo
  email:             heyunfan1996@gmail.com

# Custom vars
version:             1.0.0
